tap "adoptopenjdk/openjdk"
tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sass/sass"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "gettext"
brew "sqlite"
brew "cmake"
brew "cowsay"
brew "curl"
brew "exercism"
brew "fastlane"
brew "forego"
brew "fortune"
brew "git"
brew "libksba"
brew "gnupg"
brew "hub"
brew "imagemagick@6", link: true
brew "libxslt"
brew "postgresql"
brew "mapnik"
brew "mas"
brew "mysql"
brew "neovim"
brew "ninja"
brew "nmap"
brew "pkg-config"
brew "postgis"
brew "python"
brew "redis"
brew "ruby-build"
brew "speedtest-cli"
brew "tidy-html5"
brew "tldr"
brew "trash-cli"
brew "tree"
brew "unzip"
brew "v8@3.15"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "sass/sass/sass"
cask "1password"
cask "adoptopenjdk8"
cask "android-sdk"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "postgres"
cask "slack"
cask "visual-studio-code"
cask "wkhtmltopdf"
mas "Airmail", id: 918858936
mas "Be Focused", id: 973134470
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Smart Countdown Timer", id: 1410709951
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
