tap "adoptopenjdk/openjdk"
tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sass/sass"
tap "versent/taps"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "gettext"
brew "sqlite"
brew "awscli"
brew "cairo"
brew "cmake"
brew "cocoapods"
brew "curl"
brew "exercism"
brew "ruby"
brew "fastlane"
brew "pkg-config"
brew "unbound"
brew "srt"
brew "ffmpeg"
brew "forego"
brew "fortune"
brew "libpq"
brew "gdal"
brew "git"
brew "libksba"
brew "gnupg"
brew "helm"
brew "hub"
brew "imagemagick@6", link: true
brew "kubernetes-cli"
brew "libxslt"
brew "mas"
brew "mysql"
brew "neovim", args: ["HEAD"]
brew "ninja"
brew "nmap"
brew "node"
brew "postgresql"
brew "sfcgal"
brew "postgis"
brew "redis"
brew "ripgrep"
brew "ruby-build"
brew "skaffold"
brew "speedtest-cli"
brew "tidy-html5"
brew "tldr"
brew "tree"
brew "unzip"
brew "v8@3.15"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "sass/sass/sass"
brew "versent/taps/saml2aws"
cask "1password"
cask "adoptopenjdk8"
cask "android-sdk"
cask "firefox"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "postgres"
cask "slack"
cask "visual-studio-code"
cask "vnc-server"
cask "vnc-viewer"
cask "wkhtmltopdf"
mas "Amphetamine", id: 937984704
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Fantastical", id: 975937182
mas "Flow", id: 1423210932
mas "GoodNotes", id: 1444383602
mas "Jira", id: 1475897096
mas "Keynote", id: 409183694
mas "Okta Extension App", id: 1439967473
mas "Spark", id: 1176895641
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
